# Generated by Django 4.1 on 2022-08-13 02:46
# Generated by Django 4.1 on 2022-08-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='status_comment',
        ),
    ]
