# Generated by Django 4.1 on 2022-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usercomment_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
