# Generated by Django 4.1 on 2022-08-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
