# Generated by Django 4.1 on 2022-08-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
