# Generated by Django 4.1 on 2022-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_fess_in_world_movie_fees_in_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность'),
        ),
    ]
